/*
 * DebugTreePanel.java
 *
 * Created on 8 mars 2008, 14:25
 */

package org.siberia.ui.editor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.beans.PropertyVetoException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.tree.TreeModel;
import org.siberia.type.SibList;
import org.siberia.type.SibString;
import org.siberia.ui.swing.tree.GenericTree;
import org.siberia.ui.swing.tree.PathExpansionMode;
import org.siberia.ui.swing.tree.model.MutableTreeModel;

/**
 *
 * @author  alexis
 */
public class DebugTreePanel extends javax.swing.JPanel
{
    
    /** Creates new form DebugTreePanel */
    public DebugTreePanel()
    {
	initComponents();
	
	DefaultComboBoxModel model = new DefaultComboBoxModel();
	
	PathExpansionMode[] modes = PathExpansionMode.values();
	for(int i = 0; i < modes.length; i++)
	{
	    model.addElement(modes[i]);
	}
	
	this.comboExpandMode.setModel(model);
	
	final GenericTree tree = new GenericTree();
	
	this.comboExpandMode.addItemListener(new ItemListener()
	{
	    public void itemStateChanged(ItemEvent e)
	    {
		tree.setExpansionMode( (PathExpansionMode)comboExpandMode.getSelectedItem() );
		System.out.println("changing expansion mode to : " + comboExpandMode.getSelectedItem());
	    }
	});
	
	this.comboExpandMode.setSelectedItem(tree.getExpansionMode());
	
	this.buttonReinit.addActionListener(new ActionListener()
	{
	    public void actionPerformed(ActionEvent e)
	    {
		System.out.println("changing model");
		try
		{
		    tree.setModel(createTreeModel());
		}
		catch (PropertyVetoException ex)
		{
		    ex.printStackTrace();
		}
	    }
	});
	
	try
	{
	    tree.setModel(createTreeModel());
	}
	catch (PropertyVetoException ex)
	{
	    ex.printStackTrace();
	}
	
	this.scrollTree.setViewportView(tree);
    }
    
    /** create a new TreeModel
     *	@return a TreeModel
     */
    private TreeModel createTreeModel() throws PropertyVetoException
    {
	SibList root = new SibList();
	root.setName("root");
	
	SibList list_a = new SibList();
	list_a.setName("list a");
	
	SibList list_a_a = new SibList();
	list_a_a.setName("list a a");
	list_a.add(list_a_a);
	SibList list_a_b = new SibList();
	list_a_b.setName("list a b");
	SibString s = new SibString();
	s.setName("s_A");
	list_a_b.add(s);
	s = new SibString();
	s.setName("s_B");
	list_a_b.add(s);
	list_a.add(list_a_b);
	
	SibList list_b = new SibList();
	list_b.setName("list b");
	SibList list_c = new SibList();
	list_c.setName("list c");
	SibList list_d = new SibList();
	list_d.setName("list d");
	SibString string = new SibString();
	string.setName("string");
	
	root.add(list_a);
	root.add(list_b);
	root.add(list_c);
	root.add(list_d);
	root.add(string);
	
	MutableTreeModel model = new MutableTreeModel(root);
	
	return model;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jSplitPane1 = new javax.swing.JSplitPane();
        scrollTree = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        buttonReinit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboExpandMode = new javax.swing.JComboBox();

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setLeftComponent(scrollTree);

        buttonReinit.setText("reinit model");

        jLabel1.setText("expand mode");

        comboExpandMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonReinit)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(comboExpandMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonReinit)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboExpandMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReinit;
    private javax.swing.JComboBox comboExpandMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane scrollTree;
    // End of variables declaration//GEN-END:variables
    
}
