/*
 * blackdog : audio player / manager
 *
 * Copyright (C) 2008 Alexis PARIS
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.blackdog.ui.cover;

import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToolBar;

/**
 *
 * @author  alexis
 */
public class CoverResearchPanel extends javax.swing.JPanel
{   
    /**
     * Creates new form CoverResearchPanel
     */
    public CoverResearchPanel()
    {
	initComponents();
	
	this.messageLabel.setText("");
    }
    
    /** return the toolbar 
     *	@return a JToolBar
     */
    public JToolBar getToolBar()
    {
	return this.toolbarCovers;
    }
    
    /** return the message label
     *	@return a Label
     */
    public JLabel getMessageLabel()
    {
	return this.messageLabel;
    }
    
    /** return the main panel
     *	@return a JPanel
     */
    public JPanel getMainPanel()
    {
	return this.panelMain;
    }
    
    /** return the CardLayout of the main panel
     *	@return a CardLayout
     */
    public CardLayout getCardLayout()
    {
	return (CardLayout)this.getMainPanel().getLayout();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        toolbarCovers = new javax.swing.JToolBar();
        panelMain = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();

        toolbarCovers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        toolbarCovers.setFloatable(false);

        panelMain.setLayout(new java.awt.CardLayout());

        messageLabel.setBackground(new java.awt.Color(102, 255, 102));
        messageLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarCovers, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbarCovers, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel panelMain;
    private javax.swing.JToolBar toolbarCovers;
    // End of variables declaration//GEN-END:variables
    
}
