/*
 * ToolsFrame.java
 *
 * Created on 27 juillet 2007, 22:32
 */

package org.siberia;

import javax.swing.JMenuItem;
import org.siberia.action.ExternallyOpenPluginDeclarationAction;
import org.siberia.action.ListPluginDirAction;
import org.siberia.action.ReportingAction;

/**
 *
 * @author  alexis
 */
public class ToolsFrame extends javax.swing.JFrame
{
    /** menu item permettant de lister les plugins enregistrés */
    private JMenuItem menuListPlugins     = null;
    private JMenuItem menuOpenPluginDecls = null;
    
    /** Creates new form ToolsFrame */
    public ToolsFrame()
    {
        initComponents();
        
        this.jEditorPane1.setEditable(false);
        this.menu.setText("Actions");
        
        /** completion du menu */
        ReportingAction listPluginsAction = new ListPluginDirAction();
        listPluginsAction.setTextComponent(this.jEditorPane1);
        this.menuListPlugins = new JMenuItem(listPluginsAction);
        this.menu.add(this.menuListPlugins);
        
        ReportingAction openPluginDeclAction = new ExternallyOpenPluginDeclarationAction();
        openPluginDeclAction.setTextComponent(this.jEditorPane1);
        this.menuOpenPluginDecls = new JMenuItem(openPluginDeclAction);
        this.menu.add(this.menuOpenPluginDecls);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jScrollPane1.setViewportView(jEditorPane1);

        menu.setText("Menu");
        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ToolsFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables
    
}
